 theme: jekyll-theme-cayman
# theme: jekyll-theme-architect
# theme: jekyll-theme-minima
# 通常のパソコン（ローカル）でのテスト用
# theme: minima

# GitHub Pagesで公開するとき用（こちらが推奨される場合があります）
# remote_theme: "jekyll/minima"
# Jekyllのビルド時に data フォルダを強制的に含める設定
include:
  - data


